#!/usr/bin/env nextflow
// Auto-generated by BioPilot from a validated, schema-checked plan.
// Each process is pinned to a BioContainers image for reproducibility.
nextflow.enable.dsl=2


// Original request: find variants in these reads against the reference genome

process P_BWA_INDEX {
    container 'quay.io/biocontainers/bwa:0.7.19'
    tag 'bwa_index'

    script:
    """
    bwa index data/test/ref.fasta
    """
}

process P_FAIDX {
    container 'quay.io/biocontainers/samtools:1.23.1'
    tag 'faidx'

    script:
    """
    samtools faidx data/test/ref.fasta
    """
}

process P_BWA_MEM {
    container 'quay.io/biocontainers/bwa:0.7.19'
    tag 'bwa_mem'

    script:
    """
    bwa mem -t 2 data/test/ref.fasta data/test/reads.fastq > runs/demo/aln.sam
    """
}

process P_SAMTOOLS_SORT {
    container 'quay.io/biocontainers/samtools:1.23.1'
    tag 'samtools_sort'

    script:
    """
    samtools sort -o runs/demo/aln.sorted.bam runs/demo/aln.sam
    """
}

process P_SAMTOOLS_INDEX {
    container 'quay.io/biocontainers/samtools:1.23.1'
    tag 'samtools_index'

    script:
    """
    samtools index runs/demo/aln.sorted.bam
    """
}

process P_BCFTOOLS_MPILEUP {
    container 'quay.io/biocontainers/bcftools:1.23.1'
    tag 'bcftools_mpileup'

    script:
    """
    bcftools mpileup -f data/test/ref.fasta runs/demo/aln.sorted.bam -O u > runs/demo/pileup.bcf
    """
}

process P_BCFTOOLS_CALL {
    container 'quay.io/biocontainers/bcftools:1.23.1'
    tag 'bcftools_call'

    script:
    """
    bcftools call -mv -O v runs/demo/pileup.bcf > runs/demo/variants.vcf
    """
}

workflow {
    P_BWA_INDEX()
    P_FAIDX()
    P_BWA_MEM()
    P_SAMTOOLS_SORT()
    P_SAMTOOLS_INDEX()
    P_BCFTOOLS_MPILEUP()
    P_BCFTOOLS_CALL()
}
