"""Generate a real Nextflow DSL2 pipeline from a validated plan.

This is the *portable* reproducibility path. We do not reinvent a workflow
engine: BioPilot emits standard Nextflow that anyone can run with
``nextflow run pipeline.nf`` on any machine, with each step pinned to a
BioContainers image so the toolchain is byte-for-byte reproducible.

The generated file is also a provenance artifact in its own right: it records,
in executable form, exactly what was run.
"""
from __future__ import annotations

from ..command import Command
from ..planner.catalog import container_for, TOOL_CATALOG

_HEADER = """#!/usr/bin/env nextflow
// Auto-generated by BioPilot from a validated, schema-checked plan.
// Each process is pinned to a BioContainers image for reproducibility.
nextflow.enable.dsl=2

"""


def _process_name(step_id: str) -> str:
    return "P_" + step_id.upper().replace("-", "_")


def generate_nextflow(commands: list[Command], prompt: str = "") -> str:
    """Render the plan as a Nextflow DSL2 script (returned as a string)."""
    lines = [_HEADER]
    if prompt:
        lines.append(f"// Original request: {prompt}\n")

    proc_blocks = []
    workflow_calls = []
    for c in commands:
        spec = TOOL_CATALOG.get(c.tool)
        container = container_for(c.tool) if spec else "ubuntu:22.04"
        pname = _process_name(c.step_id)
        # The command line, exactly as validated.
        script = c.render()
        block = f"""process {pname} {{
    container '{container}'
    tag '{c.step_id}'

    script:
    \"\"\"
    {script}
    \"\"\"
}}
"""
        proc_blocks.append(block)
        workflow_calls.append(f"    {pname}()")

    lines.extend(proc_blocks)
    lines.append("workflow {\n" + "\n".join(workflow_calls) + "\n}\n")
    return "\n".join(lines)
